version: '3.8'
services:
    db:
      container_name: librarygo
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: library
      ports:
        - 5434:5432